title: Existentialism
nav_title: Existential<span class="hide-very-narrow">ism</span><br><small><span class="hide-very-narrow">with</span> University of Texas</small>

author: University of Texas at Austin
mailbox_address: ...@bristol.ac.uk

description:
  A student website to promote Existentialism

url: "https://jean-golding-institute.github.io/hackathon-template"
github_repo: jean-golding-institute

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - kierkegaard.md
  - nietzsche.md
  - heidegger.md
  - sartre.md
  - beauvoir.md
  - camus.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: demo

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: demo

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
